#######################
#auther : 猫村いちご  #
#version : 1.0.0      #
#######################
Worlds:
  - world
Tool-Settings:
  hammer01:
    Lore: 'It is Hammer!'
    Range: 1
    BlockWhitelist:
      - STONE
  hammer02:
    Lore: 'It is Hammer too!'
    Range: 2
    BlockWhitelist:
      - DIRT